version: '3.9'

services:
  db:
    image: 'postgres:latest'
    container_name: shipment_store_db
    restart: always
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mcpmwC8gGwVKr4Q9xCKZEzEgS
      - POSTGRES_DB=shipment_store
  rabbitmq:
    image: 'rabbitmq:latest'
    container_name: rabbitmqbroker
    ports:
      # AMQP protocol port
      - 5672:5672
      # HTTP management UI
      - 15672:15672

  shipmentreceiverapp:
    image: 'application:latest'
    build:
      context: .
    container_name: shipmentgeneratorapp
    depends_on:
      - db
      - rabbitmq