spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/shipment_store
    username: postgres
    password: mcpmwC8gGwVKr4Q9xCKZEzEgS
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
  kafka:
    bootstrap-servers: localhost:9092
    shipment-topic: "shipments"
    portion-topic: "portions"
    consumer:
      auto-offset-reset: earliest
      groupId: "shipment"
  feign:
    client:
      name: "personservice"
      url: "http://localhost:8081"
  rabbitmq:
    portion-queue: "portionsofshipments"
  active-broker: RABBITMQ
scheduler:
  fixed-delay: 30000
portion:
  size: 10
server:
  port: 8082