spring:
  feign:
    user-client:
      url: "http://192.168.1.1:28080"
    post-office-client:
      url: "http://192.168.1.1:8084"
    letter-client:
      url: "http://192.168.1.1:8086"
    parcel-client:
      url: "http://192.168.1.1:8087"
  datasource:
    url: jdbc:postgresql://192.168.1.1:5432/pejt_shipment
    username: postgres
    password: 1234
    hikari:
      maximum-pool-size: 3
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
  kafka:
    bootstrap-servers: 192.168.1.1:9092
    letter-topic: "letter"
    parcel-topic: "parcel"
    portion-topic: "letters"
    consumer:
      auto-offset-reset: earliest
      groupId: "shipment"
  rabbitmq:
    portion-queue: "portionsofshipments"
  active-broker: KAFKA
scheduler:
  fixed-delay: 3600000
portion:
  size: 10
server:
  port: 8082
interceptor:
  bootstrap: "192.168.1.1:9092"
  topic: "url"
